export enum ESubscriptionPlan {
  FREE = 'FREE',
  STANDARD_MONTHLY = 'STANDARD_MONTHLY',
  STANDARD_ANNUAL = 'STANDARD_ANNUAL',
  PREMIUM_MONTHLY = 'PREMIUM_MONTHLY',
  PREMIUM_ANNUAL = 'PREMIUM_ANNUAL',
}
