export enum ERaceClass {
  MAIDEN = 'MAIDEN',
  CLASS_1 = 'CLASS_1',
  CLASS_2 = 'CLASS_2',
  CLASS_3 = 'CLASS_3',
  BENCHMARK = 'BENCHMARK',
  OPEN_HANDICAP = 'OPEN_HANDICAP',
  GROUP = 'GROUP',
  LISTED = 'LISTED',
}
